name: gbm_project
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - jupyter
  - jupyterlab
  - biopython
  - networkx
  - pytorch=2.0.1
  - torchvision=0.15.2
  - rdkit
  - r-base=4.3.0
  - lightgbm
  # - r-tcgabiolinks  # Not available for osx-arm64, install in R if needed
  # - r-deseq2        # Not available for osx-arm64, install in R if needed
  # - r-edger         # Not available for osx-arm64, install in R if needed
  - pip
  - pip:
    - torch-geometric==2.3.1
    - py2neo==2021.2.4
    - rpy2==3.5.13
    - chembl-webresource-client==0.10.8
    - scanpy==1.9.3
    - anndata==0.9.2
    - leidenalg==0.10.1
    - umap-learn==0.5.3
    - lifelines==0.27.7
    - plotly==5.15.0
    - bokeh==3.2.1
    - tqdm==4.65.0
    - python-dotenv==1.0.0
    - pyyaml==6.0
    - click==8.1.6
    - xgboost==1.7.6
    - catboost==1.2.2
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - selenium==4.10.0
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - black==23.7.0
    - flake8==6.0.0
    - mypy==1.5.1 